apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-postgresql-data
  namespace: maas-keycloak
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: gp3-csi
  resources:
    requests:
      storage: 5Gi
